#!/usr/bin/env python3
"""Integrate ESP32 LAN-only profiles and serve SAME web dashboard from the ESP32.

Cloudflare is read-only; when opened at the ESP32's HTTP address, the identical
HTML/JS operates relays via same-origin POST routes. No public MQTT actuation.
"""
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'dashboard-cloudflare'
FW=ROOT/'esp32/iotmotor_esp32/iotmotor_esp32_comandos/iotmotor_esp32_comandos.ino'
HEADER=FW.with_name('iotmotor_site.h')


def once(source, old, new, label):
    count=source.count(old)
    if count != 1:
        raise RuntimeError(f'{label}: expected exactly one insertion point, got {count}')
    return source.replace(old,new,1)


def generate():
    html=(SITE/'index.html').read_text(encoding='utf-8')
    js=(SITE/'dual-dashboard.js').read_text(encoding='utf-8')
    local=(SITE/'local-controls.js').read_text(encoding='utf-8')
    # The old MQTT start buttons belonged to the retired GPIO2 prototype. They
    # remain disabled/hidden; local-controls.js provides the real four-relay UI.
    original_notice=re.search(r'<div class="notice">.*?</div>',html,re.S)
    if not original_notice: raise RuntimeError('dashboard safety banner missing')
    html=html[:original_notice.start()]+'''<div class="notice"><strong>Controle de bancada via rede local.</strong> Na mesma tela servida pelo ESP32, selecione os relés e a sequência e use Ligar/Desligar. O endereço Cloudflare exibe telemetria, mas não aciona saídas pelo MQTT público. Para energizar na bancada: jumper físico GPIO32–GND, relés SEM motor/contatores e parada local acessível. A seleção estrela/triângulo é apenas demonstração de temporização: intertravamento lógico não substitui intertravamento físico, contatores e proteções.</div>'''+html[original_notice.end():]
    html=html.replace('Saída de teste GPIO2','Saídas lógicas K1–K4 · GPIO19/18/23/27')
    html=html.replace('▶ Partida direta · bancada','Partida antiga indisponível')
    html=html.replace('Estrela-triângulo · indisponível','Protótipo antigo removido')
    html=html.replace('■ Parada</button>','Parada antiga indisponível</button>')
    html=html.replace('O ESP32-S3 é exclusivamente de sensores e nunca recebe comandos de acionamento.',
        'Configure modo de partida e relés abaixo. O ESP32-S3 mede apenas vibração e temperatura.')
    assert html.count('local-controls.js')==1 and html.count('dual-dashboard.js')==1
    (SITE/'index.html').write_text(html,encoding='utf-8')

    # Do not publish a command on the publicly writable Mosquitto broker.
    js,n=re.subn(r'function command\(kind,mode\)\{.*?\n\}\n(?=function exportCsv\()',
        "function command(kind,mode){ /* Retired GPIO2 prototype: never publish control on a public broker. */ }\n",
        js, count=1,flags=re.S)
    if n!=1 and 'Retired GPIO2 prototype' not in js: raise RuntimeError('old MQTT command handler not found')
    js=js.replace("$('startBtn').disabled=!(active&&s&&s.benchArmed&&s.voltage!==null&&s.current!==null&&!state.pending);",
                  "$('startBtn').disabled=true; // Old single-relay prototype retired.")
    js=js.replace("$('stopBtn').disabled=!state.connected; // Parada sempre possivel enquanto houver conexao, mesmo se partida estiver pendente.",
                  "$('stopBtn').disabled=true; // LAN-only control lives in local-controls.js.")
    js=js.replace("text('motorValue',active&&s.motorOn!==null?(s.motorOn?'Saída GPIO2 ligada':'Saída GPIO2 desligada'):'Não confirmado');",
        "text('motorValue',active&&Array.isArray(s?.relays)?s.relays.map((on,i)=>`K${i+1}:${on?'L':'D'}`).join(' · '):'Sem estados lógicos recentes');")
    js=js.replace("mode:typeof source.mode==='string'?source.mode:'—',vibrationPeak:numeric(source.vibration_peak)};",
        "mode:typeof source.mode==='string'?source.mode:'—',vibrationPeak:numeric(source.vibration_peak),\n  relays:Array.isArray(source.relays)&&source.relays.length===4&&source.relays.every(v=>typeof v==='boolean')?source.relays:null};")
    js=js.replace("if(which==='command'&&!hasFields&&sample.motorOn===null){",
                  "if(which==='command'&&!hasFields&&sample.motorOn===null&&!sample.relays){")
    (SITE/'dual-dashboard.js').write_text(js,encoding='utf-8')

    # Single-source web assets. This header lives next to the Arduino sketch;
    # no duplicate page must be edited when UI changes.
    html=(SITE/'index.html').read_text(encoding='utf-8')
    js=(SITE/'dual-dashboard.js').read_text(encoding='utf-8')
    local=(SITE/'local-controls.js').read_text(encoding='utf-8')
    for data,token in [(html,')IOTHTML"'),(js,')IOTDUAL"'),(local,')IOTLOCAL"')]:
        if token in data: raise RuntimeError('C++ raw-string delimiter collision')
    HEADER.write_text('''#pragma once
// AUTOMATICALLY GENERATED by tools/integrate_profiles.py. Do not edit by hand.
// Same dashboard HTML and scripts on Cloudflare and ESP32 local HTTP server.
const char INDEX_HTML[] PROGMEM = R"IOTHTML('''+html+''')IOTHTML";
const char IOTMOTOR_DUAL_JS[] PROGMEM = R"IOTDUAL('''+js+''')IOTDUAL";
const char IOTMOTOR_LOCAL_JS[] PROGMEM = R"IOTLOCAL('''+local+''')IOTLOCAL";
''',encoding='utf-8')

    source=FW.read_text(encoding='utf-8')
    pattern=r'const char INDEX_HTML\[\] PROGMEM = R"====\(.*?\)====";'
    source,n=re.subn(pattern,'#include "iotmotor_site.h"',source,count=1,flags=re.S)
    if n!=1 and '#include "iotmotor_site.h"' not in source: raise RuntimeError('original ESP32 HTML not found')
    if '#include "iotmotor_profiles.h"' not in source:
        source=once(source,'void imprimirLinhaCompleta(uint8_t linha, const char* texto) {',
                    '#include "iotmotor_profiles.h"\n\nvoid imprimirLinhaCompleta(uint8_t linha, const char* texto) {','profile header')
    if 'void tratarDualJs()' not in source:
        source=once(source,'void tratarDados() {','''void tratarDualJs() {
  adicionarCabecalhosComuns();
  server.send_P(200,"application/javascript; charset=utf-8",IOTMOTOR_DUAL_JS);
}
void tratarLocalJs() {
  adicionarCabecalhosComuns();
  server.send_P(200,"application/javascript; charset=utf-8",IOTMOTOR_LOCAL_JS);
}

void tratarDados() {''','asset routes')
    new_data='''void tratarDados() {
  StaticJsonDocument<1024> doc;
  doc["pzem_ok"] = pzemOk;
  if (pzemOk) {
    doc["tensao"] = ultimaTensao; doc["corrente"] = ultimaCorrente;
    doc["potencia"] = ultimaPotencia; doc["energia"] = ultimaEnergia;
    doc["frequencia"] = ultimaFrequencia; doc["fator_potencia"] = ultimoFatorPotencia;
  }
  doc["wifi_ok"] = WiFi.status()==WL_CONNECTED;
  if (WiFi.status()==WL_CONNECTED) doc["wifi_ip"] = WiFi.localIP().toString();
  doc["armado"] = bancadaHabilitada();
  doc["partida_etapa"] = nomeEtapa();
  doc["partida_modo"] = modoPartida==1?"sequence":"direct";
  JsonArray reles=doc.createNestedArray("reles");
  JsonArray pinos=doc.createNestedArray("relay_pins");
  for (uint8_t i=0;i<NUM_RELES;i++) { reles.add(estadoReles[i]);pinos.add(PINOS_RELES[i]); }
  JsonArray lcdLines=doc.createNestedArray("lcd");
  for (uint8_t i=0;i<LCD_LINHAS;i++) lcdLines.add(lcdCache[i]);
  String resposta; serializeJson(doc,resposta);
  adicionarCabecalhosComuns();
  server.send(200,"application/json; charset=utf-8",resposta);
}

'''
    source,n=re.subn(r'void tratarDados\(\) \{.*?\n\}\n\n(?=void tratarRele\()',lambda _:new_data,source,count=1,flags=re.S)
    if n!=1 and 'doc["partida_etapa"]' not in source: raise RuntimeError('data endpoint not found')
    source,n=re.subn(r'void tratarRele\(\) \{.*?\n\}\n\n(?=void tratarNaoEncontrado\()', '',source,count=1,flags=re.S)
    if n!=1 and 'void tratarRele()' in source: raise RuntimeError('unsafe legacy GET relay endpoint not removed')
    source=once(source,'  server.on("/dados", HTTP_GET, tratarDados);\n  server.on("/rele", HTTP_GET, tratarRele);',
        '''  server.on("/dados", HTTP_GET, tratarDados);
  server.on("/dual-dashboard.js", HTTP_GET, tratarDualJs);
  server.on("/local-controls.js", HTTP_GET, tratarLocalJs);
  server.on("/partida", HTTP_POST, tratarPartidaBancada);
  server.on("/parar", HTTP_POST, tratarPararBancada);
  server.on("/canal", HTTP_POST, tratarCanalBancada);''','HTTP routes')
    source=once(source,'  Serial.println("=== Modulo 1 / ESP32 v6 ===");',
        '  Serial.println("=== Modulo 1 / ESP32 v6 ===");\n  pinMode(PINO_HABILITACAO_BANCADA, INPUT_PULLUP);','physical enable')
    source=once(source,'  const unsigned long agora = millis();\n\n  if (agora - ultimaLeituraPzem',
        '  const unsigned long agora = millis();\n  manterPartidaBancada(agora);\n\n  if (agora - ultimaLeituraPzem','non-blocking profile tick')
    source=once(source,'  doc["seq"] = ++sequenciaMqtt;',
        '  doc["seq"] = ++sequenciaMqtt;\n  doc["bench_armed"] = bancadaHabilitada();\n  doc["start_phase"] = nomeEtapa();\n  if (WiFi.status()==WL_CONNECTED) doc["wifi_ip"] = WiFi.localIP().toString();','profile MQTT status')
    source=source.replace('  doc["mode"] = "manual_relays";',
        '  doc["mode"] = etapaPartida? (modoPartida==1?"star_delta_bench":"direct_bench") : "manual_relays";')
    source=source.replace('"v6-mqtt-mirror-1.0"','"v6-lan-profiles-1.0"')
    source=source.replace('  doc["relay_commanded_only"] = true;\n  JsonArray fields',
        '  doc["relay_commanded_only"] = true;\n  doc["lan_start_profiles"] = true;\n  doc["requires_gpio32_arm"] = true;\n  JsonArray fields')
    if 'server.on("/rele"' in source or 'mqttClient.subscribe(' in source: raise RuntimeError('public command route found')
    for anchor in ('#include "iotmotor_profiles.h"','server.on("/partida", HTTP_POST','doc["wifi_ip"]','manterPartidaBancada(agora)'):
        if anchor not in source: raise RuntimeError(f'missing {anchor}')
    FW.write_text(source,encoding='utf-8')
    print('Integrated configurable local relay profiles; shared dashboard firmware header generated; no MQTT commands.')

if __name__=='__main__': generate()
