#!/usr/bin/env python3
"""Rebuild only the generated PROGMEM assets after the one-time firmware migration.

No firmware logic, safety policy or user configuration is modified by this step.
"""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'dashboard-cloudflare'
FW=ROOT/'esp32/iotmotor_esp32/iotmotor_esp32_comandos/iotmotor_esp32_comandos.ino'
HEADER=FW.with_name('iotmotor_site.h')
assert '#include "iotmotor_site.h"' in FW.read_text(encoding='utf-8'), 'Canonical firmware not migrated'
html=(SITE/'index.html').read_text(encoding='utf-8')
js=(SITE/'dual-dashboard.js').read_text(encoding='utf-8')
local=(SITE/'local-controls.js').read_text(encoding='utf-8')
assert html.count('local-controls.js')==1 and html.count('dual-dashboard.js')==1
for content,delimiter in [(html,')IOTHTML"'),(js,')IOTDUAL"'),(local,')IOTLOCAL"')]:
    assert delimiter not in content, 'C++ literal delimiter collision'
HEADER.write_text('''#pragma once
// AUTOMATICALLY GENERATED by tools/rebuild_esp32_site.py; do not edit.
const char INDEX_HTML[] PROGMEM = R"IOTHTML('''+html+''')IOTHTML";
const char IOTMOTOR_DUAL_JS[] PROGMEM = R"IOTDUAL('''+js+''')IOTDUAL";
const char IOTMOTOR_LOCAL_JS[] PROGMEM = R"IOTLOCAL('''+local+''')IOTLOCAL";
''',encoding='utf-8')
print('ESP32 local HTML and JS synchronized with the Cloudflare dashboard.')
